```{r}
setwd("/Users/aidenstanton/projects/R")
la = read.csv("/Users/aidenstanton/projects/R/Latin-America-the-Caribbean_aggregated_data_up_to_week_of-2026-04-11.csv")
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(lsr)
library(car)
```


```{r}
la
```

```{r}
p_violence <- la %>% filter(DISORDER_TYPE == "Political violence") %>% group_by(COUNTRY) %>% summarise(total = sum(EVENTS, na.rm = TRUE))
```

```{r}
ggplot(p_violence, aes(x=total)) + geom_histogram(fill = "red", color="black", bins=20) + labs(
  title = "Political violence events across Latin America",
  x = "Number of Political Violence Events",
  y = "Countries")
```

```{r}
regional_violence <- la %>% filter(DISORDER_TYPE == "Political violence") %>% group_by(WEEK, REGION, COUNTRY) %>% summarize(country_events = sum(EVENTS), .groups = "drop")
```


```{r}
region2 <- regional_violence %>% group_by(WEEK, REGION) %>% mutate(Nearby_Country_Events = sum(country_events) - country_events)
```


```{r}
ggplot(region2, aes(x = Nearby_Country_Events)) + geom_histogram(fill = "blue", color="black", bins=20) + labs(
  title = "Political Violence in Surrounding Countries",
  x = "Events in Other Countries Occuring in the Same Region",
  y = "Number of events"
)
```

```{r}
ggplot(region2, aes(x = Nearby_Country_Events, y = country_events)) + 
  geom_point(color="orange") +
  geom_smooth(method="lm", color="blue", se=F) +
  labs(
    title = "Regional Political Violence",
    x = "Nearby Political Violence",
    y = "Domestic Political Violence"
  )
```

```{r}
sum_violence <- region2 %>% ungroup() %>% select(c(country_events, Nearby_Country_Events))

mean <- sum_violence %>% summarise(across(everything(), ~mean(.)))
median <- sum_violence %>% summarise(across(everything(), ~median(.)))
min <- sum_violence %>% summarise(across(everything(), ~min(.)))
max <- sum_violence %>% summarise(across(everything(), ~max(., na.rm=TRUE)))
iqr <- sum_violence %>% summarise(across(everything(), ~IQR(., na.rm=TRUE)))
violencestats <- data.frame(rbind(mean, median, min, max, iqr))
rownames(violencestats) <- c("mean", "median", "min", "max", "iqr")
head(violencestats)
```

```{r}
regression <- lm(formula = country_events ~ Nearby_Country_Events, data = region2)
summary(regression)
```

```{r}
group_means <- region2 %>% 
  group_by(COUNTRY) %>% 
  summarise(group_mean = mean(country_events))

group_means
```

```{r}
region2 <- region2 %>% 
  group_by(COUNTRY) %>% 
  mutate(deviation = country_events - mean(country_events)) %>% 
  mutate(sq_deviation = deviation^2)
region2
```
```{r}
within_group_violence <- sum(region2$sq_deviation)


within_group_violence
```

```{r}
samp_mean_violence <- mean(region2$country_events)
group_means <- group_means %>% 
  mutate(deviations = group_mean - samp_mean_violence) %>% 
  mutate(sq_deviations = deviations^2) %>% 
  mutate(weight_dev = sq_deviations*8) 
between_group_violence <- sum(group_means$weight_dev)

between_group_violence
```

```{r}
```

